name: Deploy Frontend
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "{{ secrets.DOCKER_PASSWORD }}" | docker login -u "{{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t jamieecode/react-test of Dockerfile.dev .
      - run: docker run -e CI=true jamieecode/react-test npm test

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          application_name: react-docker-gh-test
          environment_name: React-docker-gh-test-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-533267259028
          region: ap-northeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
